[project]
name = "seniorsinthemiddle"
version = "0.1.0"
description = "BärnHackt Seniros in the Middle"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker>=40.37.0",
    "pip>=26.2.1",
    "presidio-analyzer>=2.2.364",
    "pydantic-settings>=2.15.0",
    "tiktoken>=0.14.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
